spring:
  application:
    name: ConnectU-server
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: jinyjgo@gmail.com
    password: #
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  file:
    host: "http://localhost:8080"
    upload-dir: "C:/Users/k/Downloads/"
    max-file-size: 10MB
  coolsms:
    api:
      key: "#"
      secret: "#"
      number: "#"
server:
  servlet:
    context-path: /api

